#!/usr/bin/with-contenv bash
echo "#############################"
echo "#     BYTESIZED CONNECT     #"
echo "#   bytesized-hosting.com   #"
echo "#############################"

PUID=${PUID:-1001}
PGID=${PGID:-1000}

if [ ! "$(id -g bytesized)" -eq "$PGID" ]; then groupmod -o -g "$PGID" bytesized; fi

if [ ! "$(id -u bytesized)" -eq "$PUID" ];
  echo "Setting UID to '$PUID'"
  then usermod -o -u "$PUID" bytesized
else
  echo "UID already set correctly"
fi

for folder in config data media; do
  if [ -d /$folder ]; then
    echo "Found folder $folder, chowning"
    chown bytesized:bytesized /$folder
  fi
done
